/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.api;

import org.jhapy.mailcow.client.model.AddFwdhostBody;
import org.jhapy.mailcow.client.model.DeleteFwdhostBody;
import org.jhapy.mailcow.client.model.InlineResponse200;
import org.jhapy.mailcow.client.model.InlineResponse401;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FordwardingHostsApi
 */
@Ignore
public class FordwardingHostsApiTest {

    private final FordwardingHostsApi api = new FordwardingHostsApi();

    /**
     * Add Forward Host
     *
     * Add a new Forwarding host to mailcow. You can chose to enable or disable spam filtering of incoming emails by specifing &#x60;filter_spam&#x60; 0 &#x3D; inactive, 1 &#x3D; active.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addForwardHostTest() {
        AddFwdhostBody body = null;
        InlineResponse200 response = api.addForwardHost(body);

        // TODO: test validations
    }
    /**
     * Delete Forward Host
     *
     * Using this endpoint you can delete a forwarding host, in order to do so you need to know the IP of the host.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteForwardHostTest() {
        DeleteFwdhostBody body = null;
        InlineResponse200 response = api.deleteForwardHost(body);

        // TODO: test validations
    }
    /**
     * Get Forwarding Hosts
     *
     * You can list all Forwarding Hosts in your mailcow.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getForwardingHostsTest() {
        api.getForwardingHosts();

        // TODO: test validations
    }
}
