/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.api;

import java.math.BigDecimal;
import org.jhapy.mailcow.client.model.InlineResponse401;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LogsApi
 */
@Ignore
public class LogsApiTest {

    private final LogsApi api = new LogsApi();

    /**
     * Get ACME logs
     *
     * This Api endpoint lists all ACME logs from issued Lets Enctypts certificates. Tip: You can limit how many logs you want to get by using &#x60;/&lt;count&gt;&#x60; at the end of the api url.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getACMELogsTest() {
        BigDecimal count = null;
        String xAPIKey = null;
        api.getACMELogs(count, xAPIKey);

        // TODO: test validations
    }
    /**
     * Get Api logs
     *
     * This Api endpoint lists all Api logs. Tip: You can limit how many logs you want to get by using &#x60;/&lt;count&gt;&#x60; at the end of the api url.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getApiLogsTest() {
        BigDecimal count = null;
        String xAPIKey = null;
        api.getApiLogs(count, xAPIKey);

        // TODO: test validations
    }
    /**
     * Get Autodiscover logs
     *
     * This Api endpoint lists all Autodiscover logs. Tip: You can limit how many logs you want to get by using &#x60;/&lt;count&gt;&#x60; at the end of the api url.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAutodiscoverLogsTest() {
        BigDecimal count = null;
        String xAPIKey = null;
        api.getAutodiscoverLogs(count, xAPIKey);

        // TODO: test validations
    }
    /**
     * Get Dovecot logs
     *
     * This Api endpoint lists all Dovecot logs. Tip: You can limit how many logs you want to get by using &#x60;/&lt;count&gt;&#x60; at the end of the api url.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDovecotLogsTest() {
        BigDecimal count = null;
        String xAPIKey = null;
        api.getDovecotLogs(count, xAPIKey);

        // TODO: test validations
    }
    /**
     * Get Netfilter logs
     *
     * This Api endpoint lists all Netfilter logs. Tip: You can limit how many logs you want to get by using &#x60;/&lt;count&gt;&#x60; at the end of the api url.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNetfilterLogsTest() {
        BigDecimal count = null;
        String xAPIKey = null;
        api.getNetfilterLogs(count, xAPIKey);

        // TODO: test validations
    }
    /**
     * Get Postfix logs
     *
     * This Api endpoint lists all Postfix logs. Tip: You can limit how many logs you want to get by using &#x60;/&lt;count&gt;&#x60; at the end of the api url.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPostfixLogsTest() {
        BigDecimal count = null;
        String xAPIKey = null;
        api.getPostfixLogs(count, xAPIKey);

        // TODO: test validations
    }
    /**
     * Get Ratelimit logs
     *
     * This Api endpoint lists all Ratelimit logs. Tip: You can limit how many logs you want to get by using &#x60;/&lt;count&gt;&#x60; at the end of the api url.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRatelimitLogsTest() {
        BigDecimal count = null;
        String xAPIKey = null;
        api.getRatelimitLogs(count, xAPIKey);

        // TODO: test validations
    }
    /**
     * Get Rspamd logs
     *
     * This Api endpoint lists all Rspamd logs. Tip: You can limit how many logs you want to get by using &#x60;/&lt;count&gt;&#x60; at the end of the api url.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRspamdLogsTest() {
        BigDecimal count = null;
        String xAPIKey = null;
        api.getRspamdLogs(count, xAPIKey);

        // TODO: test validations
    }
    /**
     * Get SOGo logs
     *
     * This Api endpoint lists all SOGo logs. Tip: You can limit how many logs you want to get by using &#x60;/&lt;count&gt;&#x60; at the end of the api url.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSOGoLogsTest() {
        BigDecimal count = null;
        String xAPIKey = null;
        api.getSOGoLogs(count, xAPIKey);

        // TODO: test validations
    }
    /**
     * Get Watchdog logs
     *
     * This Api endpoint lists all Watchdog logs. Tip: You can limit how many logs you want to get by using &#x60;/&lt;count&gt;&#x60; at the end of the api url.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWatchdogLogsTest() {
        BigDecimal count = null;
        String xAPIKey = null;
        api.getWatchdogLogs(count, xAPIKey);

        // TODO: test validations
    }
}
