/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.api;

import org.jhapy.mailcow.client.model.EditRldomainBody;
import org.jhapy.mailcow.client.model.EditRlmboxBody;
import org.jhapy.mailcow.client.model.InlineResponse200;
import org.jhapy.mailcow.client.model.InlineResponse401;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RatelimitsApi
 */
@Ignore
public class RatelimitsApiTest {

    private final RatelimitsApi api = new RatelimitsApi();

    /**
     * Edit domain ratelimits
     *
     * Using this endpoint you can edit the ratelimits for a certain domains.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editDomainRatelimitsTest() {
        EditRldomainBody body = null;
        InlineResponse200 response = api.editDomainRatelimits(body);

        // TODO: test validations
    }
    /**
     * Edit mailbox ratelimits
     *
     * Using this endpoint you can edit the ratelimits for a certain mailbox.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editMailboxRatelimitsTest() {
        EditRlmboxBody body = null;
        InlineResponse200 response = api.editMailboxRatelimits(body);

        // TODO: test validations
    }
    /**
     * Get domain ratelimits
     *
     * Using this endpoint you can get the ratelimits for a certain domains. You can use all for all domain.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDomainRatelimitsTest() {
        String domain = null;
        String xAPIKey = null;
        api.getDomainRatelimits(domain, xAPIKey);

        // TODO: test validations
    }
    /**
     * Get mailbox ratelimits
     *
     * Using this endpoint you can get the ratelimits for a certain mailbox. You can use all for all mailboxes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMailboxRatelimitsTest() {
        String mailbox = null;
        String xAPIKey = null;
        api.getMailboxRatelimits(mailbox, xAPIKey);

        // TODO: test validations
    }
}
