/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.api;

import org.jhapy.mailcow.client.model.AddSyncjobBody;
import org.jhapy.mailcow.client.model.DeleteSyncjobBody;
import org.jhapy.mailcow.client.model.EditSyncjobBody;
import org.jhapy.mailcow.client.model.InlineResponse200;
import org.jhapy.mailcow.client.model.InlineResponse401;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SyncJobsApi
 */
@Ignore
public class SyncJobsApiTest {

    private final SyncJobsApi api = new SyncJobsApi();

    /**
     * Create sync job
     *
     * You can create new sync job using this action. It takes a JSON object containing a domain informations.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSyncJobTest() {
        AddSyncjobBody body = null;
        InlineResponse200 response = api.createSyncJob(body);

        // TODO: test validations
    }
    /**
     * Delete sync job
     *
     * You can delete one or more sync jobs.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSyncJobTest() {
        DeleteSyncjobBody body = null;
        InlineResponse200 response = api.deleteSyncJob(body);

        // TODO: test validations
    }
    /**
     * Get sync jobs
     *
     * You can list all syn jobs existing in system.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSyncJobsTest() {
        api.getSyncJobs();

        // TODO: test validations
    }
    /**
     * Update sync job
     *
     * You can update one or more sync jobs per request. You can also send just attributes you want to change.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSyncJobTest() {
        EditSyncjobBody body = null;
        InlineResponse200 response = api.updateSyncJob(body);

        // TODO: test validations
    }
}
