/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AddDomainpolicyBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-23T22:25:19.320233+01:00[Africa/Casablanca]")
public class AddDomainpolicyBody {
  @JsonProperty("domain")
  private String domain = null;

  @JsonProperty("object_from")
  private String objectFrom = null;

  /**
   * Gets or Sets objectList
   */
  public enum ObjectListEnum {
    WL("wl"),
    BL("bl");

    private String value;

    ObjectListEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ObjectListEnum fromValue(String text) {
      for (ObjectListEnum b : ObjectListEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("object_list")
  private ObjectListEnum objectList = null;

  public AddDomainpolicyBody domain(String domain) {
    this.domain = domain;
    return this;
  }

   /**
   * domain name to which policy is associated to
   * @return domain
  **/
  @Schema(description = "domain name to which policy is associated to")
  public String getDomain() {
    return domain;
  }

  public void setDomain(String domain) {
    this.domain = domain;
  }

  public AddDomainpolicyBody objectFrom(String objectFrom) {
    this.objectFrom = objectFrom;
    return this;
  }

   /**
   * exact address or use wildcard to match whole domain
   * @return objectFrom
  **/
  @Schema(description = "exact address or use wildcard to match whole domain")
  public String getObjectFrom() {
    return objectFrom;
  }

  public void setObjectFrom(String objectFrom) {
    this.objectFrom = objectFrom;
  }

  public AddDomainpolicyBody objectList(ObjectListEnum objectList) {
    this.objectList = objectList;
    return this;
  }

   /**
   * Get objectList
   * @return objectList
  **/
  @Schema(description = "")
  public ObjectListEnum getObjectList() {
    return objectList;
  }

  public void setObjectList(ObjectListEnum objectList) {
    this.objectList = objectList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddDomainpolicyBody addDomainpolicyBody = (AddDomainpolicyBody) o;
    return Objects.equals(this.domain, addDomainpolicyBody.domain) &&
        Objects.equals(this.objectFrom, addDomainpolicyBody.objectFrom) &&
        Objects.equals(this.objectList, addDomainpolicyBody.objectList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domain, objectFrom, objectList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddDomainpolicyBody {\n");
    
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    objectFrom: ").append(toIndentedString(objectFrom)).append("\n");
    sb.append("    objectList: ").append(toIndentedString(objectList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
