/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
/**
 * AddResourceBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-23T22:25:19.320233+01:00[Africa/Casablanca]")
public class AddResourceBody {
  @JsonProperty("active")
  private BigDecimal active = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("domain")
  private String domain = null;

  /**
   * the kind of recouse
   */
  public enum KindEnum {
    LOCATION("location"),
    GROUP("group"),
    THING("thing");

    private String value;

    KindEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static KindEnum fromValue(String text) {
      for (KindEnum b : KindEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("kind")
  private KindEnum kind = null;

  /**
   * Gets or Sets multipleBookings
   */
  public enum MultipleBookingsEnum {
    _1("-1"),
    _1_1("1"),
    CUSTOM("custom");

    private String value;

    MultipleBookingsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static MultipleBookingsEnum fromValue(String text) {
      for (MultipleBookingsEnum b : MultipleBookingsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("multiple_bookings")
  private MultipleBookingsEnum multipleBookings = null;

  @JsonProperty("multiple_bookings_custom")
  private BigDecimal multipleBookingsCustom = null;

  /**
   * Gets or Sets multipleBookingsSelect
   */
  public enum MultipleBookingsSelectEnum {
    _1("-1"),
    _1_1("1"),
    CUSTOM("custom");

    private String value;

    MultipleBookingsSelectEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static MultipleBookingsSelectEnum fromValue(String text) {
      for (MultipleBookingsSelectEnum b : MultipleBookingsSelectEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("multiple_bookings_select")
  private MultipleBookingsSelectEnum multipleBookingsSelect = null;

  public AddResourceBody active(BigDecimal active) {
    this.active = active;
    return this;
  }

   /**
   * 1 for a active transport map 0 for a disabled transport map
   * @return active
  **/
  @Schema(description = "1 for a active transport map 0 for a disabled transport map")
  public BigDecimal getActive() {
    return active;
  }

  public void setActive(BigDecimal active) {
    this.active = active;
  }

  public AddResourceBody description(String description) {
    this.description = description;
    return this;
  }

   /**
   * a description of the resource
   * @return description
  **/
  @Schema(description = "a description of the resource")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AddResourceBody domain(String domain) {
    this.domain = domain;
    return this;
  }

   /**
   * the domain for which the resource should be
   * @return domain
  **/
  @Schema(description = "the domain for which the resource should be")
  public String getDomain() {
    return domain;
  }

  public void setDomain(String domain) {
    this.domain = domain;
  }

  public AddResourceBody kind(KindEnum kind) {
    this.kind = kind;
    return this;
  }

   /**
   * the kind of recouse
   * @return kind
  **/
  @Schema(description = "the kind of recouse")
  public KindEnum getKind() {
    return kind;
  }

  public void setKind(KindEnum kind) {
    this.kind = kind;
  }

  public AddResourceBody multipleBookings(MultipleBookingsEnum multipleBookings) {
    this.multipleBookings = multipleBookings;
    return this;
  }

   /**
   * Get multipleBookings
   * @return multipleBookings
  **/
  @Schema(description = "")
  public MultipleBookingsEnum getMultipleBookings() {
    return multipleBookings;
  }

  public void setMultipleBookings(MultipleBookingsEnum multipleBookings) {
    this.multipleBookings = multipleBookings;
  }

  public AddResourceBody multipleBookingsCustom(BigDecimal multipleBookingsCustom) {
    this.multipleBookingsCustom = multipleBookingsCustom;
    return this;
  }

   /**
   * always empty
   * @return multipleBookingsCustom
  **/
  @Schema(description = "always empty")
  public BigDecimal getMultipleBookingsCustom() {
    return multipleBookingsCustom;
  }

  public void setMultipleBookingsCustom(BigDecimal multipleBookingsCustom) {
    this.multipleBookingsCustom = multipleBookingsCustom;
  }

  public AddResourceBody multipleBookingsSelect(MultipleBookingsSelectEnum multipleBookingsSelect) {
    this.multipleBookingsSelect = multipleBookingsSelect;
    return this;
  }

   /**
   * Get multipleBookingsSelect
   * @return multipleBookingsSelect
  **/
  @Schema(description = "")
  public MultipleBookingsSelectEnum getMultipleBookingsSelect() {
    return multipleBookingsSelect;
  }

  public void setMultipleBookingsSelect(MultipleBookingsSelectEnum multipleBookingsSelect) {
    this.multipleBookingsSelect = multipleBookingsSelect;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddResourceBody addResourceBody = (AddResourceBody) o;
    return Objects.equals(this.active, addResourceBody.active) &&
        Objects.equals(this.description, addResourceBody.description) &&
        Objects.equals(this.domain, addResourceBody.domain) &&
        Objects.equals(this.kind, addResourceBody.kind) &&
        Objects.equals(this.multipleBookings, addResourceBody.multipleBookings) &&
        Objects.equals(this.multipleBookingsCustom, addResourceBody.multipleBookingsCustom) &&
        Objects.equals(this.multipleBookingsSelect, addResourceBody.multipleBookingsSelect);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, description, domain, kind, multipleBookings, multipleBookingsCustom, multipleBookingsSelect);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddResourceBody {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    multipleBookings: ").append(toIndentedString(multipleBookings)).append("\n");
    sb.append("    multipleBookingsCustom: ").append(toIndentedString(multipleBookingsCustom)).append("\n");
    sb.append("    multipleBookingsSelect: ").append(toIndentedString(multipleBookingsSelect)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
