/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
/**
 * Apiv1editrlmboxAttr
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-23T22:25:19.320233+01:00[Africa/Casablanca]")
public class Apiv1editrlmboxAttr {
  @JsonProperty("rl_frame")
  private String rlFrame = null;

  @JsonProperty("rl_vlaue")
  private BigDecimal rlVlaue = null;

  public Apiv1editrlmboxAttr rlFrame(String rlFrame) {
    this.rlFrame = rlFrame;
    return this;
  }

   /**
   * contains the frame for the ratelimit h,s,m
   * @return rlFrame
  **/
  @Schema(description = "contains the frame for the ratelimit h,s,m")
  public String getRlFrame() {
    return rlFrame;
  }

  public void setRlFrame(String rlFrame) {
    this.rlFrame = rlFrame;
  }

  public Apiv1editrlmboxAttr rlVlaue(BigDecimal rlVlaue) {
    this.rlVlaue = rlVlaue;
    return this;
  }

   /**
   * contains the rate for the ratelimit 10,20,50,1
   * @return rlVlaue
  **/
  @Schema(description = "contains the rate for the ratelimit 10,20,50,1")
  public BigDecimal getRlVlaue() {
    return rlVlaue;
  }

  public void setRlVlaue(BigDecimal rlVlaue) {
    this.rlVlaue = rlVlaue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1editrlmboxAttr apiv1editrlmboxAttr = (Apiv1editrlmboxAttr) o;
    return Objects.equals(this.rlFrame, apiv1editrlmboxAttr.rlFrame) &&
        Objects.equals(this.rlVlaue, apiv1editrlmboxAttr.rlVlaue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rlFrame, rlVlaue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1editrlmboxAttr {\n");
    
    sb.append("    rlFrame: ").append(toIndentedString(rlFrame)).append("\n");
    sb.append("    rlVlaue: ").append(toIndentedString(rlVlaue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
