/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
/**
 * Apiv1editpushoverAttr
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-23T22:25:19.320233+01:00[Africa/Casablanca]")
public class Apiv1editpushoverAttr {
  @JsonProperty("active")
  private BigDecimal active = null;

  @JsonProperty("evaluate_x_prio")
  private BigDecimal evaluateXPrio = null;

  @JsonProperty("key")
  private String key = null;

  @JsonProperty("only_x_prio")
  private BigDecimal onlyXPrio = null;

  @JsonProperty("senders")
  private String senders = null;

  @JsonProperty("senders_regex")
  private String sendersRegex = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("token")
  private String token = null;

  public Apiv1editpushoverAttr active(BigDecimal active) {
    this.active = active;
    return this;
  }

   /**
   * Enables pushover 1 disable pushover 0
   * @return active
  **/
  @Schema(description = "Enables pushover 1 disable pushover 0")
  public BigDecimal getActive() {
    return active;
  }

  public void setActive(BigDecimal active) {
    this.active = active;
  }

  public Apiv1editpushoverAttr evaluateXPrio(BigDecimal evaluateXPrio) {
    this.evaluateXPrio = evaluateXPrio;
    return this;
  }

   /**
   * Send the Push with High priority
   * @return evaluateXPrio
  **/
  @Schema(description = "Send the Push with High priority")
  public BigDecimal getEvaluateXPrio() {
    return evaluateXPrio;
  }

  public void setEvaluateXPrio(BigDecimal evaluateXPrio) {
    this.evaluateXPrio = evaluateXPrio;
  }

  public Apiv1editpushoverAttr key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Pushover key
   * @return key
  **/
  @Schema(description = "Pushover key")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public Apiv1editpushoverAttr onlyXPrio(BigDecimal onlyXPrio) {
    this.onlyXPrio = onlyXPrio;
    return this;
  }

   /**
   * Only send push for prio mails
   * @return onlyXPrio
  **/
  @Schema(description = "Only send push for prio mails")
  public BigDecimal getOnlyXPrio() {
    return onlyXPrio;
  }

  public void setOnlyXPrio(BigDecimal onlyXPrio) {
    this.onlyXPrio = onlyXPrio;
  }

  public Apiv1editpushoverAttr senders(String senders) {
    this.senders = senders;
    return this;
  }

   /**
   * Only send push for emails from these senders
   * @return senders
  **/
  @Schema(description = "Only send push for emails from these senders")
  public String getSenders() {
    return senders;
  }

  public void setSenders(String senders) {
    this.senders = senders;
  }

  public Apiv1editpushoverAttr sendersRegex(String sendersRegex) {
    this.sendersRegex = sendersRegex;
    return this;
  }

   /**
   * Regex to match senders for which a push will be send
   * @return sendersRegex
  **/
  @Schema(description = "Regex to match senders for which a push will be send")
  public String getSendersRegex() {
    return sendersRegex;
  }

  public void setSendersRegex(String sendersRegex) {
    this.sendersRegex = sendersRegex;
  }

  public Apiv1editpushoverAttr text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Custom push noficiation text
   * @return text
  **/
  @Schema(description = "Custom push noficiation text")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public Apiv1editpushoverAttr title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Push title
   * @return title
  **/
  @Schema(description = "Push title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Apiv1editpushoverAttr token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Pushover token
   * @return token
  **/
  @Schema(description = "Pushover token")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1editpushoverAttr apiv1editpushoverAttr = (Apiv1editpushoverAttr) o;
    return Objects.equals(this.active, apiv1editpushoverAttr.active) &&
        Objects.equals(this.evaluateXPrio, apiv1editpushoverAttr.evaluateXPrio) &&
        Objects.equals(this.key, apiv1editpushoverAttr.key) &&
        Objects.equals(this.onlyXPrio, apiv1editpushoverAttr.onlyXPrio) &&
        Objects.equals(this.senders, apiv1editpushoverAttr.senders) &&
        Objects.equals(this.sendersRegex, apiv1editpushoverAttr.sendersRegex) &&
        Objects.equals(this.text, apiv1editpushoverAttr.text) &&
        Objects.equals(this.title, apiv1editpushoverAttr.title) &&
        Objects.equals(this.token, apiv1editpushoverAttr.token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, evaluateXPrio, key, onlyXPrio, senders, sendersRegex, text, title, token);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1editpushoverAttr {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    evaluateXPrio: ").append(toIndentedString(evaluateXPrio)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    onlyXPrio: ").append(toIndentedString(onlyXPrio)).append("\n");
    sb.append("    senders: ").append(toIndentedString(senders)).append("\n");
    sb.append("    sendersRegex: ").append(toIndentedString(sendersRegex)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
