/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Apiv1edituseraclAttr
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-23T22:25:19.320233+01:00[Africa/Casablanca]")
public class Apiv1edituseraclAttr {
  @JsonProperty("user_acl")
  private Object userAcl = null;

  public Apiv1edituseraclAttr userAcl(Object userAcl) {
    this.userAcl = userAcl;
    return this;
  }

   /**
   * contains a list of active user acls
   * @return userAcl
  **/
  @Schema(description = "contains a list of active user acls")
  public Object getUserAcl() {
    return userAcl;
  }

  public void setUserAcl(Object userAcl) {
    this.userAcl = userAcl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1edituseraclAttr apiv1edituseraclAttr = (Apiv1edituseraclAttr) o;
    return Objects.equals(this.userAcl, apiv1edituseraclAttr.userAcl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userAcl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1edituseraclAttr {\n");
    
    sb.append("    userAcl: ").append(toIndentedString(userAcl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
