/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
/**
 * Apiv1editdomainAttr
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-23T22:25:19.320233+01:00[Africa/Casablanca]")
public class Apiv1editdomainAttr {
  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("aliases")
  private BigDecimal aliases = null;

  @JsonProperty("backupmx")
  private Boolean backupmx = null;

  @JsonProperty("defquota")
  private BigDecimal defquota = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("gal")
  private Boolean gal = null;

  @JsonProperty("mailboxes")
  private BigDecimal mailboxes = null;

  @JsonProperty("maxquota")
  private BigDecimal maxquota = null;

  @JsonProperty("quota")
  private BigDecimal quota = null;

  @JsonProperty("relay_all_recipients")
  private Boolean relayAllRecipients = null;

  @JsonProperty("relayhost")
  private BigDecimal relayhost = null;

  public Apiv1editdomainAttr active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * is domain active or not
   * @return active
  **/
  @Schema(description = "is domain active or not")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Apiv1editdomainAttr aliases(BigDecimal aliases) {
    this.aliases = aliases;
    return this;
  }

   /**
   * limit count of aliases associated with this domain
   * @return aliases
  **/
  @Schema(description = "limit count of aliases associated with this domain")
  public BigDecimal getAliases() {
    return aliases;
  }

  public void setAliases(BigDecimal aliases) {
    this.aliases = aliases;
  }

  public Apiv1editdomainAttr backupmx(Boolean backupmx) {
    this.backupmx = backupmx;
    return this;
  }

   /**
   * relay domain or not
   * @return backupmx
  **/
  @Schema(description = "relay domain or not")
  public Boolean isBackupmx() {
    return backupmx;
  }

  public void setBackupmx(Boolean backupmx) {
    this.backupmx = backupmx;
  }

  public Apiv1editdomainAttr defquota(BigDecimal defquota) {
    this.defquota = defquota;
    return this;
  }

   /**
   * predefined mailbox quota in &#x60;add mailbox&#x60; form
   * @return defquota
  **/
  @Schema(description = "predefined mailbox quota in `add mailbox` form")
  public BigDecimal getDefquota() {
    return defquota;
  }

  public void setDefquota(BigDecimal defquota) {
    this.defquota = defquota;
  }

  public Apiv1editdomainAttr description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of domain
   * @return description
  **/
  @Schema(description = "Description of domain")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Apiv1editdomainAttr gal(Boolean gal) {
    this.gal = gal;
    return this;
  }

   /**
   * is domain global address list active or not, it enables shared contacts accross domain in SOGo webmail
   * @return gal
  **/
  @Schema(description = "is domain global address list active or not, it enables shared contacts accross domain in SOGo webmail")
  public Boolean isGal() {
    return gal;
  }

  public void setGal(Boolean gal) {
    this.gal = gal;
  }

  public Apiv1editdomainAttr mailboxes(BigDecimal mailboxes) {
    this.mailboxes = mailboxes;
    return this;
  }

   /**
   * limit count of mailboxes associated with this domain
   * @return mailboxes
  **/
  @Schema(description = "limit count of mailboxes associated with this domain")
  public BigDecimal getMailboxes() {
    return mailboxes;
  }

  public void setMailboxes(BigDecimal mailboxes) {
    this.mailboxes = mailboxes;
  }

  public Apiv1editdomainAttr maxquota(BigDecimal maxquota) {
    this.maxquota = maxquota;
    return this;
  }

   /**
   * maximum quota per mailbox
   * @return maxquota
  **/
  @Schema(description = "maximum quota per mailbox")
  public BigDecimal getMaxquota() {
    return maxquota;
  }

  public void setMaxquota(BigDecimal maxquota) {
    this.maxquota = maxquota;
  }

  public Apiv1editdomainAttr quota(BigDecimal quota) {
    this.quota = quota;
    return this;
  }

   /**
   * maximum quota for this domain (for all mailboxes in sum)
   * @return quota
  **/
  @Schema(description = "maximum quota for this domain (for all mailboxes in sum)")
  public BigDecimal getQuota() {
    return quota;
  }

  public void setQuota(BigDecimal quota) {
    this.quota = quota;
  }

  public Apiv1editdomainAttr relayAllRecipients(Boolean relayAllRecipients) {
    this.relayAllRecipients = relayAllRecipients;
    return this;
  }

   /**
   * if not, them you have to create \&quot;dummy\&quot; mailbox for each address to relay
   * @return relayAllRecipients
  **/
  @Schema(description = "if not, them you have to create \"dummy\" mailbox for each address to relay")
  public Boolean isRelayAllRecipients() {
    return relayAllRecipients;
  }

  public void setRelayAllRecipients(Boolean relayAllRecipients) {
    this.relayAllRecipients = relayAllRecipients;
  }

  public Apiv1editdomainAttr relayhost(BigDecimal relayhost) {
    this.relayhost = relayhost;
    return this;
  }

   /**
   * id of relayhost
   * @return relayhost
  **/
  @Schema(description = "id of relayhost")
  public BigDecimal getRelayhost() {
    return relayhost;
  }

  public void setRelayhost(BigDecimal relayhost) {
    this.relayhost = relayhost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1editdomainAttr apiv1editdomainAttr = (Apiv1editdomainAttr) o;
    return Objects.equals(this.active, apiv1editdomainAttr.active) &&
        Objects.equals(this.aliases, apiv1editdomainAttr.aliases) &&
        Objects.equals(this.backupmx, apiv1editdomainAttr.backupmx) &&
        Objects.equals(this.defquota, apiv1editdomainAttr.defquota) &&
        Objects.equals(this.description, apiv1editdomainAttr.description) &&
        Objects.equals(this.gal, apiv1editdomainAttr.gal) &&
        Objects.equals(this.mailboxes, apiv1editdomainAttr.mailboxes) &&
        Objects.equals(this.maxquota, apiv1editdomainAttr.maxquota) &&
        Objects.equals(this.quota, apiv1editdomainAttr.quota) &&
        Objects.equals(this.relayAllRecipients, apiv1editdomainAttr.relayAllRecipients) &&
        Objects.equals(this.relayhost, apiv1editdomainAttr.relayhost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, aliases, backupmx, defquota, description, gal, mailboxes, maxquota, quota, relayAllRecipients, relayhost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1editdomainAttr {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    aliases: ").append(toIndentedString(aliases)).append("\n");
    sb.append("    backupmx: ").append(toIndentedString(backupmx)).append("\n");
    sb.append("    defquota: ").append(toIndentedString(defquota)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    gal: ").append(toIndentedString(gal)).append("\n");
    sb.append("    mailboxes: ").append(toIndentedString(mailboxes)).append("\n");
    sb.append("    maxquota: ").append(toIndentedString(maxquota)).append("\n");
    sb.append("    quota: ").append(toIndentedString(quota)).append("\n");
    sb.append("    relayAllRecipients: ").append(toIndentedString(relayAllRecipients)).append("\n");
    sb.append("    relayhost: ").append(toIndentedString(relayhost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
