/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
/**
 * Apiv1editmailboxAttr
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-23T22:25:19.320233+01:00[Africa/Casablanca]")
public class Apiv1editmailboxAttr {
  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("force_pw_update")
  private Boolean forcePwUpdate = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("password2")
  private String password2 = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("quota")
  private BigDecimal quota = null;

  @JsonProperty("sender_acl")
  private Object senderAcl = null;

  @JsonProperty("sogo_access")
  private Boolean sogoAccess = null;

  public Apiv1editmailboxAttr active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * is mailbox active or not
   * @return active
  **/
  @Schema(description = "is mailbox active or not")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Apiv1editmailboxAttr forcePwUpdate(Boolean forcePwUpdate) {
    this.forcePwUpdate = forcePwUpdate;
    return this;
  }

   /**
   * force user to change password on next login
   * @return forcePwUpdate
  **/
  @Schema(description = "force user to change password on next login")
  public Boolean isForcePwUpdate() {
    return forcePwUpdate;
  }

  public void setForcePwUpdate(Boolean forcePwUpdate) {
    this.forcePwUpdate = forcePwUpdate;
  }

  public Apiv1editmailboxAttr name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Full name of the mailbox user
   * @return name
  **/
  @Schema(description = "Full name of the mailbox user")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Apiv1editmailboxAttr password2(String password2) {
    this.password2 = password2;
    return this;
  }

   /**
   * new mailbox password for confirmation
   * @return password2
  **/
  @Schema(description = "new mailbox password for confirmation")
  public String getPassword2() {
    return password2;
  }

  public void setPassword2(String password2) {
    this.password2 = password2;
  }

  public Apiv1editmailboxAttr password(String password) {
    this.password = password;
    return this;
  }

   /**
   * new mailbox password
   * @return password
  **/
  @Schema(description = "new mailbox password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public Apiv1editmailboxAttr quota(BigDecimal quota) {
    this.quota = quota;
    return this;
  }

   /**
   * mailbox quota
   * @return quota
  **/
  @Schema(description = "mailbox quota")
  public BigDecimal getQuota() {
    return quota;
  }

  public void setQuota(BigDecimal quota) {
    this.quota = quota;
  }

  public Apiv1editmailboxAttr senderAcl(Object senderAcl) {
    this.senderAcl = senderAcl;
    return this;
  }

   /**
   * list of allowed send from addresses
   * @return senderAcl
  **/
  @Schema(description = "list of allowed send from addresses")
  public Object getSenderAcl() {
    return senderAcl;
  }

  public void setSenderAcl(Object senderAcl) {
    this.senderAcl = senderAcl;
  }

  public Apiv1editmailboxAttr sogoAccess(Boolean sogoAccess) {
    this.sogoAccess = sogoAccess;
    return this;
  }

   /**
   * is access to SOGo webmail active or not
   * @return sogoAccess
  **/
  @Schema(description = "is access to SOGo webmail active or not")
  public Boolean isSogoAccess() {
    return sogoAccess;
  }

  public void setSogoAccess(Boolean sogoAccess) {
    this.sogoAccess = sogoAccess;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1editmailboxAttr apiv1editmailboxAttr = (Apiv1editmailboxAttr) o;
    return Objects.equals(this.active, apiv1editmailboxAttr.active) &&
        Objects.equals(this.forcePwUpdate, apiv1editmailboxAttr.forcePwUpdate) &&
        Objects.equals(this.name, apiv1editmailboxAttr.name) &&
        Objects.equals(this.password2, apiv1editmailboxAttr.password2) &&
        Objects.equals(this.password, apiv1editmailboxAttr.password) &&
        Objects.equals(this.quota, apiv1editmailboxAttr.quota) &&
        Objects.equals(this.senderAcl, apiv1editmailboxAttr.senderAcl) &&
        Objects.equals(this.sogoAccess, apiv1editmailboxAttr.sogoAccess);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, forcePwUpdate, name, password2, password, quota, senderAcl, sogoAccess);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1editmailboxAttr {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    forcePwUpdate: ").append(toIndentedString(forcePwUpdate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    password2: ").append(toIndentedString(password2)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    quota: ").append(toIndentedString(quota)).append("\n");
    sb.append("    senderAcl: ").append(toIndentedString(senderAcl)).append("\n");
    sb.append("    sogoAccess: ").append(toIndentedString(sogoAccess)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
