/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Apiv1editdaaclAttr
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-23T22:25:19.320233+01:00[Africa/Casablanca]")
public class Apiv1editdaaclAttr {
  @JsonProperty("da_acl")
  private Object daAcl = null;

  public Apiv1editdaaclAttr daAcl(Object daAcl) {
    this.daAcl = daAcl;
    return this;
  }

   /**
   * contains the list of acl names that are active for this user
   * @return daAcl
  **/
  @Schema(description = "contains the list of acl names that are active for this user")
  public Object getDaAcl() {
    return daAcl;
  }

  public void setDaAcl(Object daAcl) {
    this.daAcl = daAcl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1editdaaclAttr apiv1editdaaclAttr = (Apiv1editdaaclAttr) o;
    return Objects.equals(this.daAcl, apiv1editdaaclAttr.daAcl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(daAcl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1editdaaclAttr {\n");
    
    sb.append("    daAcl: ").append(toIndentedString(daAcl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
