/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Apiv1editquarantineNotificationAttr
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-23T22:25:19.320233+01:00[Africa/Casablanca]")
public class Apiv1editquarantineNotificationAttr {
  /**
   * recurrence
   */
  public enum QuarantineNotificationEnum {
    HOURLY("hourly"),
    DAILY("daily"),
    WEEKLY("weekly"),
    NEVER("never");

    private String value;

    QuarantineNotificationEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static QuarantineNotificationEnum fromValue(String text) {
      for (QuarantineNotificationEnum b : QuarantineNotificationEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("quarantine_notification")
  private QuarantineNotificationEnum quarantineNotification = null;

  public Apiv1editquarantineNotificationAttr quarantineNotification(QuarantineNotificationEnum quarantineNotification) {
    this.quarantineNotification = quarantineNotification;
    return this;
  }

   /**
   * recurrence
   * @return quarantineNotification
  **/
  @Schema(description = "recurrence")
  public QuarantineNotificationEnum getQuarantineNotification() {
    return quarantineNotification;
  }

  public void setQuarantineNotification(QuarantineNotificationEnum quarantineNotification) {
    this.quarantineNotification = quarantineNotification;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1editquarantineNotificationAttr apiv1editquarantineNotificationAttr = (Apiv1editquarantineNotificationAttr) o;
    return Objects.equals(this.quarantineNotification, apiv1editquarantineNotificationAttr.quarantineNotification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quarantineNotification);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1editquarantineNotificationAttr {\n");
    
    sb.append("    quarantineNotification: ").append(toIndentedString(quarantineNotification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
