/*
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jhapy.mailcow.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * Mailbox
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-23T22:25:19.320233+01:00[Africa/Casablanca]")
public class Mailbox {
  @JsonProperty("username")
  private String username = null;

  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("relayhost")
  private String relayhost = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("local_part")
  private String localPart = null;

  @JsonProperty("quota")
  private BigDecimal quota = null;

  @JsonProperty("messages")
  private BigDecimal messages = null;

  @JsonProperty("attributes")
  private Map<String, String> attributes = null;

  @JsonProperty("quota_used")
  private BigDecimal quotaUsed = null;

  @JsonProperty("percent_in_use")
  private String percentInUse = null;

  @JsonProperty("percent_class")
  private String percentClass = null;

  @JsonProperty("last_imap_login")
  private BigDecimal lastImapLogin = null;

  @JsonProperty("last_smtp_login")
  private BigDecimal lastSmtpLogin = null;

  @JsonProperty("last_pop3_login")
  private BigDecimal lastPop3Login = null;

  @JsonProperty("max_new_quota")
  private BigDecimal maxNewQuota = null;

  @JsonProperty("spam_aliases")
  private BigDecimal spamAliases = null;

  @JsonProperty("pushover_active")
  private BigDecimal pushoverActive = null;

  @JsonProperty("rl")
  private Boolean rl = null;

  @JsonProperty("rl_scope")
  private String rlScope = null;

  @JsonProperty("is_relayed")
  private BigDecimal isRelayed = null;

  public Mailbox username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @Schema(description = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public Mailbox active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @Schema(description = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Mailbox relayhost(String relayhost) {
    this.relayhost = relayhost;
    return this;
  }

   /**
   * Get relayhost
   * @return relayhost
  **/
  @Schema(description = "")
  public String getRelayhost() {
    return relayhost;
  }

  public void setRelayhost(String relayhost) {
    this.relayhost = relayhost;
  }

  public Mailbox name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Mailbox localPart(String localPart) {
    this.localPart = localPart;
    return this;
  }

   /**
   * Get localPart
   * @return localPart
  **/
  @Schema(description = "")
  public String getLocalPart() {
    return localPart;
  }

  public void setLocalPart(String localPart) {
    this.localPart = localPart;
  }

  public Mailbox quota(BigDecimal quota) {
    this.quota = quota;
    return this;
  }

   /**
   * Get quota
   * @return quota
  **/
  @Schema(description = "")
  public BigDecimal getQuota() {
    return quota;
  }

  public void setQuota(BigDecimal quota) {
    this.quota = quota;
  }

  public Mailbox messages(BigDecimal messages) {
    this.messages = messages;
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @Schema(description = "")
  public BigDecimal getMessages() {
    return messages;
  }

  public void setMessages(BigDecimal messages) {
    this.messages = messages;
  }

  public Mailbox attributes(Map<String, String> attributes) {
    this.attributes = attributes;
    return this;
  }

  public Mailbox putAttributesItem(String key, String attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<String, String>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @Schema(description = "")
  public Map<String, String> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, String> attributes) {
    this.attributes = attributes;
  }

  public Mailbox quotaUsed(BigDecimal quotaUsed) {
    this.quotaUsed = quotaUsed;
    return this;
  }

   /**
   * Get quotaUsed
   * @return quotaUsed
  **/
  @Schema(description = "")
  public BigDecimal getQuotaUsed() {
    return quotaUsed;
  }

  public void setQuotaUsed(BigDecimal quotaUsed) {
    this.quotaUsed = quotaUsed;
  }

  public Mailbox percentInUse(String percentInUse) {
    this.percentInUse = percentInUse;
    return this;
  }

   /**
   * Get percentInUse
   * @return percentInUse
  **/
  @Schema(description = "")
  public String getPercentInUse() {
    return percentInUse;
  }

  public void setPercentInUse(String percentInUse) {
    this.percentInUse = percentInUse;
  }

  public Mailbox percentClass(String percentClass) {
    this.percentClass = percentClass;
    return this;
  }

   /**
   * Get percentClass
   * @return percentClass
  **/
  @Schema(description = "")
  public String getPercentClass() {
    return percentClass;
  }

  public void setPercentClass(String percentClass) {
    this.percentClass = percentClass;
  }

  public Mailbox lastImapLogin(BigDecimal lastImapLogin) {
    this.lastImapLogin = lastImapLogin;
    return this;
  }

   /**
   * Get lastImapLogin
   * @return lastImapLogin
  **/
  @Schema(description = "")
  public BigDecimal getLastImapLogin() {
    return lastImapLogin;
  }

  public void setLastImapLogin(BigDecimal lastImapLogin) {
    this.lastImapLogin = lastImapLogin;
  }

  public Mailbox lastSmtpLogin(BigDecimal lastSmtpLogin) {
    this.lastSmtpLogin = lastSmtpLogin;
    return this;
  }

   /**
   * Get lastSmtpLogin
   * @return lastSmtpLogin
  **/
  @Schema(description = "")
  public BigDecimal getLastSmtpLogin() {
    return lastSmtpLogin;
  }

  public void setLastSmtpLogin(BigDecimal lastSmtpLogin) {
    this.lastSmtpLogin = lastSmtpLogin;
  }

  public Mailbox lastPop3Login(BigDecimal lastPop3Login) {
    this.lastPop3Login = lastPop3Login;
    return this;
  }

   /**
   * Get lastPop3Login
   * @return lastPop3Login
  **/
  @Schema(description = "")
  public BigDecimal getLastPop3Login() {
    return lastPop3Login;
  }

  public void setLastPop3Login(BigDecimal lastPop3Login) {
    this.lastPop3Login = lastPop3Login;
  }

  public Mailbox maxNewQuota(BigDecimal maxNewQuota) {
    this.maxNewQuota = maxNewQuota;
    return this;
  }

   /**
   * Get maxNewQuota
   * @return maxNewQuota
  **/
  @Schema(description = "")
  public BigDecimal getMaxNewQuota() {
    return maxNewQuota;
  }

  public void setMaxNewQuota(BigDecimal maxNewQuota) {
    this.maxNewQuota = maxNewQuota;
  }

  public Mailbox spamAliases(BigDecimal spamAliases) {
    this.spamAliases = spamAliases;
    return this;
  }

   /**
   * Get spamAliases
   * @return spamAliases
  **/
  @Schema(description = "")
  public BigDecimal getSpamAliases() {
    return spamAliases;
  }

  public void setSpamAliases(BigDecimal spamAliases) {
    this.spamAliases = spamAliases;
  }

  public Mailbox pushoverActive(BigDecimal pushoverActive) {
    this.pushoverActive = pushoverActive;
    return this;
  }

   /**
   * Get pushoverActive
   * @return pushoverActive
  **/
  @Schema(description = "")
  public BigDecimal getPushoverActive() {
    return pushoverActive;
  }

  public void setPushoverActive(BigDecimal pushoverActive) {
    this.pushoverActive = pushoverActive;
  }

  public Mailbox rl(Boolean rl) {
    this.rl = rl;
    return this;
  }

   /**
   * Get rl
   * @return rl
  **/
  @Schema(description = "")
  public Boolean isRl() {
    return rl;
  }

  public void setRl(Boolean rl) {
    this.rl = rl;
  }

  public Mailbox rlScope(String rlScope) {
    this.rlScope = rlScope;
    return this;
  }

   /**
   * Get rlScope
   * @return rlScope
  **/
  @Schema(description = "")
  public String getRlScope() {
    return rlScope;
  }

  public void setRlScope(String rlScope) {
    this.rlScope = rlScope;
  }

  public Mailbox isRelayed(BigDecimal isRelayed) {
    this.isRelayed = isRelayed;
    return this;
  }

   /**
   * Get isRelayed
   * @return isRelayed
  **/
  @Schema(description = "")
  public BigDecimal getIsRelayed() {
    return isRelayed;
  }

  public void setIsRelayed(BigDecimal isRelayed) {
    this.isRelayed = isRelayed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mailbox mailbox = (Mailbox) o;
    return Objects.equals(this.username, mailbox.username) &&
        Objects.equals(this.active, mailbox.active) &&
        Objects.equals(this.relayhost, mailbox.relayhost) &&
        Objects.equals(this.name, mailbox.name) &&
        Objects.equals(this.localPart, mailbox.localPart) &&
        Objects.equals(this.quota, mailbox.quota) &&
        Objects.equals(this.messages, mailbox.messages) &&
        Objects.equals(this.attributes, mailbox.attributes) &&
        Objects.equals(this.quotaUsed, mailbox.quotaUsed) &&
        Objects.equals(this.percentInUse, mailbox.percentInUse) &&
        Objects.equals(this.percentClass, mailbox.percentClass) &&
        Objects.equals(this.lastImapLogin, mailbox.lastImapLogin) &&
        Objects.equals(this.lastSmtpLogin, mailbox.lastSmtpLogin) &&
        Objects.equals(this.lastPop3Login, mailbox.lastPop3Login) &&
        Objects.equals(this.maxNewQuota, mailbox.maxNewQuota) &&
        Objects.equals(this.spamAliases, mailbox.spamAliases) &&
        Objects.equals(this.pushoverActive, mailbox.pushoverActive) &&
        Objects.equals(this.rl, mailbox.rl) &&
        Objects.equals(this.rlScope, mailbox.rlScope) &&
        Objects.equals(this.isRelayed, mailbox.isRelayed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, active, relayhost, name, localPart, quota, messages, attributes, quotaUsed, percentInUse, percentClass, lastImapLogin, lastSmtpLogin, lastPop3Login, maxNewQuota, spamAliases, pushoverActive, rl, rlScope, isRelayed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mailbox {\n");
    
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    relayhost: ").append(toIndentedString(relayhost)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    localPart: ").append(toIndentedString(localPart)).append("\n");
    sb.append("    quota: ").append(toIndentedString(quota)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    quotaUsed: ").append(toIndentedString(quotaUsed)).append("\n");
    sb.append("    percentInUse: ").append(toIndentedString(percentInUse)).append("\n");
    sb.append("    percentClass: ").append(toIndentedString(percentClass)).append("\n");
    sb.append("    lastImapLogin: ").append(toIndentedString(lastImapLogin)).append("\n");
    sb.append("    lastSmtpLogin: ").append(toIndentedString(lastSmtpLogin)).append("\n");
    sb.append("    lastPop3Login: ").append(toIndentedString(lastPop3Login)).append("\n");
    sb.append("    maxNewQuota: ").append(toIndentedString(maxNewQuota)).append("\n");
    sb.append("    spamAliases: ").append(toIndentedString(spamAliases)).append("\n");
    sb.append("    pushoverActive: ").append(toIndentedString(pushoverActive)).append("\n");
    sb.append("    rl: ").append(toIndentedString(rl)).append("\n");
    sb.append("    rlScope: ").append(toIndentedString(rlScope)).append("\n");
    sb.append("    isRelayed: ").append(toIndentedString(isRelayed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
